/*
 *  Copyright (C) 2005-2022 Team Kodi
 *  This file is part of Kodi - https://kodi.tv
 *
 *  SPDX-License-Identifier: GPL-2.0-or-later
 *  See LICENSES/README.md for more information.
 */

/* File autogenerated, see xbmc/addons/kodi-dev-kit/tools/code-generator/code_generator.py */

#pragma once

#include "core/IMsgHdl.h"
#include "src/shared/api/addon-instance/web.h"

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1_END>---*/

namespace KODI
{
namespace ADDONS
{
namespace INTERFACE
{

struct directFuncToAddon_addoninstance_web_h;
struct directFuncToKodi_addoninstance_web_h;

} /* namespace INTERFACE */
} /* namespace ADDONS */
} /* namespace KODI */

namespace KODI_ADDON
{
namespace INTERNAL
{

class ATTR_DLL_LOCAL CHdl_kodi_addoninstance_web_h : public IMsgHdl
{
public:
  CHdl_kodi_addoninstance_web_h(AddonIfc* ifc) : IMsgHdl(ifc) {}

  void InitDirect(KODI::ADDONS::INTERFACE::directFuncToAddon_addoninstance_web_h* ifcToAddon);

#ifndef KODI_INHIBIT_SHARED
  bool HandleMessage(int funcGroup,
                     int func,
                     const msgpack::unpacked& in,
                     msgpack::sbuffer& out) override;
#endif /* !KODI_INHIBIT_SHARED */

  /* Code below becomes on auto generation reused, hand edited parts should included here */
  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2>---*/
  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2_END>---*/

  // Calls from Kodi to addon
  static enum WEB_ADDON_ERROR kodi_addon_web_start_instance_v1(
      void* thisClassHdl, const KODI_ADDON_WEB_HDL hdl); // Added with API 1

  static void kodi_addon_web_stop_instance_v1(void* thisClassHdl,
                                              const KODI_ADDON_WEB_HDL hdl); // Added with API 1

  static bool kodi_addon_web_main_initialize_v1(void* thisClassHdl,
                                                const KODI_ADDON_WEB_HDL hdl); // Added with API 1

  static void kodi_addon_web_main_loop_v1(void* thisClassHdl,
                                          const KODI_ADDON_WEB_HDL hdl); // Added with API 1

  static void kodi_addon_web_main_shutdown_v1(void* thisClassHdl,
                                              const KODI_ADDON_WEB_HDL hdl); // Added with API 1

  static void kodi_addon_web_set_mute_v1(void* thisClassHdl,
                                         const KODI_ADDON_WEB_HDL hdl,
                                         bool mute); // Added with API 1

  static bool kodi_addon_web_set_language_v1(void* thisClassHdl,
                                             const KODI_ADDON_WEB_HDL hdl,
                                             const char* language); // Added with API 1

  static enum WEB_ADDON_ERROR kodi_addon_web_create_control_v1(
      void* thisClassHdl,
      const KODI_ADDON_WEB_HDL hdl,
      const struct WEB_ADDON_GUI_PROPS* props,
      const char* start_url,
      WEB_KODI_CONTROL* handle); // Added with API 1

  static enum WEB_ADDON_ERROR kodi_addon_web_destroy_control_v1(void* thisClassHdl,
                                                                const KODI_ADDON_WEB_HDL hdl,
                                                                const WEB_KODI_CONTROL handle,
                                                                bool complete); // Added with API 1

  static bool kodi_addon_web_control_render_init_v1(
      void* thisClassHdl,
      const KODI_ADDON_WEB_HDL hdl,
      const WEB_KODI_CONTROL handle); // Added with API 1

  static void kodi_addon_web_control_render_deinit_v1(
      void* thisClassHdl,
      const KODI_ADDON_WEB_HDL hdl,
      const WEB_KODI_CONTROL handle); // Added with API 1

  static void kodi_addon_web_control_render_v1(void* thisClassHdl,
                                               const KODI_ADDON_WEB_HDL hdl,
                                               const WEB_KODI_CONTROL handle); // Added with API 1

  static bool kodi_addon_web_control_dirty_v1(void* thisClassHdl,
                                              const KODI_ADDON_WEB_HDL hdl,
                                              const WEB_KODI_CONTROL handle); // Added with API 1

  static bool kodi_addon_web_control_on_init_v1(void* thisClassHdl,
                                                const KODI_ADDON_WEB_HDL hdl,
                                                const WEB_KODI_CONTROL handle); // Added with API 1

  static bool kodi_addon_web_control_on_action_v1(void* thisClassHdl,
                                                  const KODI_ADDON_WEB_HDL hdl,
                                                  const WEB_KODI_CONTROL handle,
                                                  const struct KODI_ADDON_ACTION_DATA* action,
                                                  int* nextItem); // Added with API 1

  static bool kodi_addon_web_control_on_mouse_event_v1(void* thisClassHdl,
                                                       const KODI_ADDON_WEB_HDL hdl,
                                                       const WEB_KODI_CONTROL handle,
                                                       int id,
                                                       double x,
                                                       double y,
                                                       double offsetX,
                                                       double offsetY,
                                                       int state); // Added with API 1

  static bool kodi_addon_web_control_open_website_v1(void* thisClassHdl,
                                                     const KODI_ADDON_WEB_HDL hdl,
                                                     const WEB_KODI_CONTROL handle,
                                                     const char* url); // Added with API 1

  static bool kodi_addon_web_control_get_history_v1(void* thisClassHdl,
                                                    const KODI_ADDON_WEB_HDL hdl,
                                                    const WEB_KODI_CONTROL handle,
                                                    char*** list,
                                                    size_t* entries,
                                                    bool behind_current); // Added with API 1

  static void kodi_addon_web_control_search_text_v1(void* thisClassHdl,
                                                    const KODI_ADDON_WEB_HDL hdl,
                                                    const WEB_KODI_CONTROL handle,
                                                    const char* text,
                                                    bool forward,
                                                    bool matchCase,
                                                    bool findNext); // Added with API 1

  static void kodi_addon_web_control_stop_search_v1(void* thisClassHdl,
                                                    const KODI_ADDON_WEB_HDL hdl,
                                                    const WEB_KODI_CONTROL handle,
                                                    bool clearSelection); // Added with API 1

  static void kodi_addon_web_control_web_cmd_reload_v1(
      void* thisClassHdl,
      const KODI_ADDON_WEB_HDL hdl,
      const WEB_KODI_CONTROL handle); // Added with API 1

  static void kodi_addon_web_control_web_cmd_stop_load_v1(
      void* thisClassHdl,
      const KODI_ADDON_WEB_HDL hdl,
      const WEB_KODI_CONTROL handle); // Added with API 1

  static void kodi_addon_web_control_web_cmd_nav_back_v1(
      void* thisClassHdl,
      const KODI_ADDON_WEB_HDL hdl,
      const WEB_KODI_CONTROL handle); // Added with API 1

  static void kodi_addon_web_control_web_cmd_nav_forward_v1(
      void* thisClassHdl,
      const KODI_ADDON_WEB_HDL hdl,
      const WEB_KODI_CONTROL handle); // Added with API 1

  static void kodi_addon_web_control_web_open_own_context_menu_v1(
      void* thisClassHdl,
      const KODI_ADDON_WEB_HDL hdl,
      const WEB_KODI_CONTROL handle); // Added with API 1

  static void kodi_addon_web_control_screen_size_change_v1(void* thisClassHdl,
                                                           const KODI_ADDON_WEB_HDL hdl,
                                                           const WEB_KODI_CONTROL handle,
                                                           float x,
                                                           float y,
                                                           float width,
                                                           float height,
                                                           bool fullscreen); // Added with API 1
};

} /* namespace INTERNAL */
} /* namespace KODI_ADDON */
