/*
 *  Copyright (C) 2005-2022 Team Kodi
 *  This file is part of Kodi - https://kodi.tv
 *
 *  SPDX-License-Identifier: GPL-2.0-or-later
 *  See LICENSES/README.md for more information.
 */

/* File autogenerated, see xbmc/addons/kodi-dev-kit/tools/code-generator/code_generator.py */

#pragma once

#include "../../../../../include/kodi/c-api/gui/input/action.h"
#include "src/shared/SharedGroups.h"

#include <string.h>
#include <string>
#include <tuple>
#include <vector>

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1_END>---*/

#ifndef MSGPACK_ADD_ENUM_ADDON_ACTION
#define MSGPACK_ADD_ENUM_ADDON_ACTION
MSGPACK_ADD_ENUM(ADDON_ACTION);
#endif

namespace KODI
{
namespace ADDONS
{
namespace INTERFACE
{

struct IFC_KODI_ADDON_ACTION_DATA
{
  IFC_KODI_ADDON_ACTION_DATA() = default;
  IFC_KODI_ADDON_ACTION_DATA(const KODI_ADDON_ACTION_DATA* c_data)
  {
    if (c_data == nullptr)
      return;

    id = c_data->id;
    if (c_data->name)
      name = c_data->name;
    memcpy(amount.data(), c_data->amount, ADDON_ACTION_AMOUNT_MAX);
    repeat = c_data->repeat;
    hold_time = c_data->hold_time;
    button_code = c_data->button_code;
    unicode = c_data->unicode;
    if (c_data->text)
      text = c_data->text;
  }

  void SetCStructure(KODI_ADDON_ACTION_DATA* c_data)
  {
    if (c_data == nullptr)
      return;

    c_data->id = id;
    c_data->name = name.c_str();
    memcpy(c_data->amount, amount.data(), ADDON_ACTION_AMOUNT_MAX);
    c_data->repeat = repeat;
    c_data->hold_time = hold_time;
    c_data->button_code = button_code;
    c_data->unicode = unicode;
    c_data->text = text.c_str();
  }

  enum ADDON_ACTION id;
  std::string name;
  std::array<float, ADDON_ACTION_AMOUNT_MAX> amount;
  float repeat;
  unsigned int hold_time;
  unsigned int button_code;
  wchar_t unicode;
  std::string text;

  MSGPACK_DEFINE(id, name, amount, repeat, hold_time, button_code, unicode, text);
};

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2_END>---*/

} /* namespace INTERFACE */
} /* namespace ADDONS */
} /* namespace KODI */
