/*
 *  Copyright (C) 2005-2022 Team Kodi
 *  This file is part of Kodi - https://kodi.tv
 *
 *  SPDX-License-Identifier: GPL-2.0-or-later
 *  See LICENSES/README.md for more information.
 */

/* File autogenerated, see xbmc/addons/kodi-dev-kit/tools/code-generator/code_generator.py */

#pragma once

#include "addons/interface/IMsgHdl.h"

// API include
#include "addons/kodi-dev-kit/include/kodi/c-api/addon-instance/screensaver.h"

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1_END>---*/

namespace KODI
{
namespace ADDONS
{
namespace INTERFACE
{

class IOffscreenRenderProcess;
struct directFuncToAddon_addoninstance_screensaver_h;
struct directFuncToKodi_addoninstance_screensaver_h;

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2_END>---*/

class CHdl_kodi_addoninstance_screensaver_h : public IMsgHdl
{
public:
  CHdl_kodi_addoninstance_screensaver_h(CInterface& interface) : IMsgHdl(interface) {}

  void InitDirect(directFuncToKodi_addoninstance_screensaver_h* ifcToKodi,
                  directFuncToAddon_addoninstance_screensaver_h* ifcToAddon);

  // To handle callbacks from addon by shared sandbox API (static functions below in private becomes used)
  bool HandleMessage(int funcGroup,
                     int func,
                     const msgpack::unpacked& in,
                     msgpack::sbuffer& out) override;

  /* Code below becomes on auto generation reused, hand edited parts should included here */
  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_3>---*/
  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_3_END>---*/

  // Function calls from Kodi to addon

  bool kodi_addon_screensaver_start_v1(IOffscreenRenderProcess* proc,
                                       const KODI_ADDON_SCREENSAVER_HDL hdl); // Added with API 1

  void kodi_addon_screensaver_stop_v1(IOffscreenRenderProcess* proc,
                                      const KODI_ADDON_SCREENSAVER_HDL hdl); // Added with API 1

  void kodi_addon_screensaver_render_v1(IOffscreenRenderProcess* proc,
                                        const KODI_ADDON_SCREENSAVER_HDL hdl); // Added with API 1

private:
  /* Code below becomes on auto generation reused, hand edited parts should included here */
  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_4>---*/
  /*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_4_END>---*/

  // Callbacks from addon to Kodi
  static void kodi_addon_screensaver_get_properties_v1(
      void* thisClassHdl,
      const KODI_ADDON_INSTANCE_BACKEND_HDL hdl,
      struct KODI_ADDON_SCREENSAVER_PROPS* props); // Added with API 1

  directFuncToAddon_addoninstance_screensaver_h* m_ifcToAddon{nullptr};
};

} /* namespace INTERFACE */
} /* namespace ADDONS */
} /* namespace KODI */
