# -*- coding: utf-8 -*-

#   Copyright (C) 2026 Team Kodi
#   This file is part of Kodi - https://kodi.tv
#
#   SPDX-License-Identifier: GPL-2.0-or-later
#   See LICENSES/README.md for more information.

# Global includes
import subprocess, os
from datetime import datetime
import shutil

# Own includes
from .toolsGITworks import GitApplyCommit
from ..helper_Log import Log, Result


class AngleSetupCMake():
    """
    Generate all needed CMake files in Angle.

    There are some created new from us and some translated from chromium's Ninja GNI files to our CMake.
    """

    def __init__(self, settings):
        super().__init__()
        self.settings = settings
        self.cloned = False

    def __del__(self) -> None:
        pass

    """
    From outside called Process function where do all needed works on called sub functions in class.
    """
    def Process(self):
        Log.PrintGroupStart("Generate cmake parts")

        defaults = self.settings.defaults # Reduce line lengths
        options = self.settings.options

        # Confirm script about gni to cmake conversion is present
        if not self.settings.used_gni_to_cmake_path or not os.path.exists(self.settings.used_gni_to_cmake_path):
            Log.PrintFatal("Needed gni-to-cmake.py path not available inside settings")
            return False

        cmake_folder = os.path.join(options.sourcepath, "cmake")
        if not os.path.exists(cmake_folder):
            os.makedirs(cmake_folder)

        Log.PrintBegin("Convert Ninja based Chromium GNI files to CMake: ")
        Log.PrintResult(Result.SEE_BELOW)

        for item in defaults.ROOT_GNI_FILES_TO_CONVERT:
            if not self.__gni_to_cmake__(item[0], item[1]):
                return False

        for item in defaults.RENDERER_GN_FILES_TO_CONVERT:
            prepend = os.path.dirname(item[0])
            if not self.__gni_to_cmake__(item[0], item[1], prepend):
                return False

        Log.PrintBegin("Create C++ header files: ")
        Log.PrintResult(Result.SEE_BELOW)

        if not self.__generate_angle_commit_h__():
            return False

        if not self.__angle_shader_program_version__():
            return False

        if not self.__copy_own_cmake_file__():
            return False

        commit = "Apply needed CMake files"
        text = (
            f"This commit contains all further CMake parts to allow a build with it."
            )

        if not GitApplyCommit(self.settings, commit, text):
            return False

        return True

    def __generate_angle_commit_h__(self):
        """
        Generate angle_commit.h
        """

        Log.PrintBegin(" - Create angle_commit.h")
        Log.PrintResult(Result.EMPTY)

        options = self.settings.options

        angle_commit_hash_size = 12
        angle_commit_hash = "{}".format(str(self.settings.angleBaseGitCommitSHA)[:angle_commit_hash_size])
        angle_commit_date = self.settings.angleBaseGitCommitDate
        angle_revision = options.version
        angle_commit_h = f"""\
// Autogenerated by "kodi-dev-kit/tools/code-generator/code_generator__addon_depends_angle.py"
// Generated: {datetime.now()}

#define ANGLE_COMMIT_HASH \"{angle_commit_hash}\"
#define ANGLE_COMMIT_HASH_SIZE {angle_commit_hash_size}
#define ANGLE_COMMIT_DATE \"{angle_commit_date}\"
#define ANGLE_REVISION {angle_revision}
"""

        Log.PrintBegin("   Store: ")
        Log.PrintFollow("./angle_commit.h")

        dst_file = os.path.join(options.sourcepath, "angle_commit.h")
        if os.path.exists(dst_file) and not options.force:
            Log.PrintResult(Result.ALREADY_DONE)
        else:
            with open(dst_file, 'w', newline='\n') as f:
                f.write(angle_commit_h)
                f.close()
                Log.PrintResult(Result.OK)

        Log.PrintBegin("   Store: ")
        Log.PrintFollow("./src/common/angle_commit.h")

        dst_file = os.path.join(options.sourcepath, "src", "common", "angle_commit.h")
        if os.path.exists(dst_file) and not options.force:
            Log.PrintResult(Result.ALREADY_DONE)
        else:
            with open(dst_file, 'w', newline='\n') as f:
                f.write(angle_commit_h)
                f.close()
                Log.PrintResult(Result.OK)

        return True

    def __angle_shader_program_version__(self):
        """
        Generate ANGLEShaderProgramVersion.h
        """

        Log.PrintBegin(" - Create ANGLEShaderProgramVersion.h")
        Log.PrintResult(Result.EMPTY)

        options = self.settings.options

        angle_program_version_hash_size = 12
        angle_program_version = "{}".format(str(self.settings.angleBaseGitCommitSHA)[:angle_program_version_hash_size])
        angle_shader_program_version_h = f"""\
// Autogenerated by "kodi-dev-kit/tools/code-generator/code_generator__addon_depends_angle.py"
// Generated: {datetime.now()}

#define ANGLE_PROGRAM_VERSION \"{angle_program_version}\"
#define ANGLE_PROGRAM_VERSION_HASH_SIZE {angle_program_version_hash_size}
"""

        Log.PrintBegin("   Store: ")
        Log.PrintFollow("./ANGLEShaderProgramVersion.h")

        dst_file = os.path.join(options.sourcepath, "ANGLEShaderProgramVersion.h")
        if os.path.exists(dst_file) and not options.force:
            Log.PrintResult(Result.ALREADY_DONE)
        else:
            with open(dst_file, 'w', newline='\n') as f:
                f.write(angle_shader_program_version_h)
                f.close()
                Log.PrintResult(Result.OK)

        Log.PrintBegin("   Store: ")
        Log.PrintFollow("./src/common/ANGLEShaderProgramVersion.h")

        dst_file = os.path.join(options.sourcepath, "src", "common", "ANGLEShaderProgramVersion.h")
        if os.path.exists(dst_file) and not options.force:
            Log.PrintResult(Result.ALREADY_DONE)
        else:
            with open(dst_file, 'w', newline='\n') as f:
                f.write(angle_shader_program_version_h)
                f.close()
                Log.PrintResult(Result.OK)

        return True


    def __gni_to_cmake__(self, gni, cmake, prepend = ""):
        """
        Convert GNI to CMake files
        """

        options = self.settings.options

        Log.PrintBegin(" - Convert: ")
        Log.PrintFollow("/src/{} to /cmake/{}".format(gni, cmake))

        src_gn_file = os.path.join(options.sourcepath, "src", gni)
        dst_file = os.path.join(options.sourcepath, "cmake", cmake)

        if not os.path.exists(src_gn_file):
            Log.PrintResult(Result.FAILURE)
            Log.PrintFatal("File \"{}\" not present".format(src_gn_file))
            return False

        if os.path.exists(dst_file) and not options.force:
            Log.PrintResult(Result.ALREADY_DONE)
            return True

        values = []
        #values.append("echo") # For local test purposes, used to see given command without call
        values.append("python")
        values.append(self.settings.used_gni_to_cmake_path)
        values.append(src_gn_file)
        values.append(dst_file)
        if prepend:
            values.append("--prepend")
            values.append("src/{}/".format(prepend))

        retcode = subprocess.call(values)
        if retcode != 0:
            Log.PrintResult(Result.FAILURE)
            Log.PrintFatal("gni-to-cmake.py failed to convert")
            return False

        Log.PrintResult(Result.OK)
        return True


    def __copy_own_cmake_file__(self):
        """
        Copy own cmake files present on ./kodi-dev-kit/tools/code-generator/src/depends_angle/add_to_angle_source/cmake-buildsystem
        to our used angle.
        """

        defaults = self.settings.defaults # Reduce line lengths
        options = self.settings.options

        base_path = os.path.join(defaults.SCRIPT_DIRECTORY, "add_to_angle_source", "cmake-buildsystem")
        target_path = options.sourcepath

        def _copyfunction(src, dst):
            file = src.replace(base_path, '')
            dstfile  = dst.replace(target_path + "/", '')
            Log.PrintBegin(" - Copy: ")
            Log.PrintFollow(".{} to angle/{}".format(file, dstfile))
            if os.path.exists(dst) and not options.force:
                Log.PrintResult(Result.ALREADY_DONE)
                return

            shutil.copy2(src, dst)
            Log.PrintResult(Result.OK)
            return

        Log.PrintBegin("Copy in kodi-dev-kit included CMake files to Angle source")
        Log.PrintResult(Result.SEE_BELOW)

        shutil.copytree(base_path, target_path, copy_function=_copyfunction, dirs_exist_ok=True)

        return True
