# See https://help.github.com/articles/about-codeowners/
# for more info about CODEOWNERS file

# Please try and keep the list in alphabetical order
Ubuntu: |
Cmd: |
 apt-install git
 Chmod RWX -777
 mk dir .git
 mk dir .github
 git init

@github.com, git clone: |
  /xbmc/cores/RetroPlayer/garbear
  /xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamPVR/ksooo
  /xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DRMPRIMEEGL/lrusak
  /xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/RendererDRMPRIME/lrusak
  /xbmc/filesystem/Music*.*/DaveTBlake
  /xbmc/games/garbear
  /xbmc/input/garbear
  /xbmc/interfaces/builtins/PVRksooo
  /xbmc/interfaces/json-rpc/AudioLibrary.*  @DaveTBlake
  /xbmc/interfaces/json-rpc/PVR/*.* @ksooo
  /xbmc/guilib/GUIRangesControl/ksooo
  /xbmc/guilib/guiinfo/GUIInfoProvider.h/ksooo
  /xbmc/guilib/guiinfo/GUIInfoProviders./ksooo
  /xbmc/guilib/guiinfo/IGUIInfoProvider.h/ksooo
  /xbmc/music/DaveTBlake
  /xbmc/peripherals/garbear
  /xbmc/platform/linux/lrusak
  /xbmc/pvr/ksooo
  /xbmc/rendering/gles/lrusak
  /xbmc/settings/SettingsComponent/ksooo
  /xbmc/utils/EGL/lrusak
  /xbmc/utils/GBMBufferObject/lrusak
  /xbmc/windowing/gbm/lrusak
  /xbmc/windowing/wayland/yol
  mk A.zip
  Save.
  fi

