list(APPEND CORE_MAIN_SOURCE ${CMAKE_SOURCE_DIR}/xbmc/platform/darwin/osx/XBMCApplication.mm)

if(NOT APP_RENDER_SYSTEM OR APP_RENDER_SYSTEM STREQUAL "vulkan")
  list(APPEND PLATFORM_REQUIRED_DEPS Vulkan VulkanMemoryAllocator GLM)
  set(APP_RENDER_SYSTEM vulkan)
elseif(APP_RENDER_SYSTEM STREQUAL "gl")
  list(APPEND PLATFORM_REQUIRED_DEPS OpenGl)
  list(APPEND SYSTEM_DEFINES -DGL_DO_NOT_WARN_IF_MULTI_GL_VERSION_HEADERS_INCLUDED
                             -DGL_SILENCE_DEPRECATION)
else()
  message(SEND_ERROR "Currently only Vulkan or OpenGL rendering is supported. Please set APP_RENDER_SYSTEM to \"vulkan\" or \"gl\"")
endif()

set(${CORE_SYSTEM_NAME}_SEARCH_CONFIG NO_DEFAULT_PATH CACHE STRING "")
list(APPEND PLATFORM_REQUIRED_DEPS Smctemp>=0.4.0)

list(APPEND PLATFORM_OPTIONAL_PACKAGES LibAACS LibBDPlus)
