/*
 *  Copyright (C) 2005-2022 Team Kodi
 *  This file is part of Kodi - https://kodi.tv
 *
 *  SPDX-License-Identifier: GPL-2.0-or-later
 *  See LICENSES/README.md for more information.
 */

/* File autogenerated, see xbmc/addons/kodi-dev-kit/tools/code-generator/code_generator.py */

#pragma once

#include "../../../include/kodi/c-api/addon_base.h"
#include "src/shared/SharedGroups.h"

#include <string.h>
#include <string>
#include <tuple>
#include <vector>

/* API struct from 1 to 1 */
typedef struct KODI_ADDON_FUNC_V1_TO_V1
{
  PFN_KODI_ADDON_CREATE_V1 create; /*---AUTO<EQUAL_FROM_TO:1_1>---*/
  PFN_KODI_ADDON_DESTROY_V1 destroy; /*---AUTO<EQUAL_FROM_TO:1_1>---*/
  PFN_KODI_ADDON_SETTING_CHANGE_STRING_V1 setting_change_string; /*---AUTO<EQUAL_FROM_TO:1_1>---*/
  PFN_KODI_ADDON_SETTING_CHANGE_BOOLEAN_V1 setting_change_boolean; /*---AUTO<EQUAL_FROM_TO:1_1>---*/
  PFN_KODI_ADDON_SETTING_CHANGE_INTEGER_V1 setting_change_integer; /*---AUTO<EQUAL_FROM_TO:1_1>---*/
  PFN_KODI_ADDON_SETTING_CHANGE_FLOAT_V1 setting_change_float; /*---AUTO<EQUAL_FROM_TO:1_1>---*/
  PFN_KODI_ADDON_CREATE_INSTANCE_V1 create_instance; /*---AUTO<EQUAL_FROM_TO:1_1>---*/
  PFN_KODI_ADDON_DESTROY_INSTANCE_V1 destroy_instance; /*---AUTO<EQUAL_FROM_TO:1_1>---*/
  PFN_KODI_ADDON_INSTANCE_SETTING_CHANGE_STRING_V1
      instance_setting_change_string; /*---AUTO<EQUAL_FROM_TO:1_1>---*/
  PFN_KODI_ADDON_INSTANCE_SETTING_CHANGE_BOOLEAN_V1
      instance_setting_change_boolean; /*---AUTO<EQUAL_FROM_TO:1_1>---*/
  PFN_KODI_ADDON_INSTANCE_SETTING_CHANGE_INTEGER_V1
      instance_setting_change_integer; /*---AUTO<EQUAL_FROM_TO:1_1>---*/
  PFN_KODI_ADDON_INSTANCE_SETTING_CHANGE_FLOAT_V1
      instance_setting_change_float; /*---AUTO<EQUAL_FROM_TO:1_1>---*/
} KODI_ADDON_FUNC_V1_TO_V1;

union KODI_ADDON_FUNC_UNION
{
  struct KODI_ADDON_FUNC_V1_TO_V1 v1;
};

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1>---*/

union KODI_ADDON_INSTANCE_FUNC_UNION
{
  struct KODI_ADDON_INSTANCE_FUNC v1;
};

/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_1_END>---*/

#ifndef MSGPACK_ADD_ENUM_KODI_ADDON_INSTANCE_TYPE
#define MSGPACK_ADD_ENUM_KODI_ADDON_INSTANCE_TYPE
MSGPACK_ADD_ENUM(KODI_ADDON_INSTANCE_TYPE);
#endif
#ifndef MSGPACK_ADD_ENUM_ADDON_STATUS
#define MSGPACK_ADD_ENUM_ADDON_STATUS
MSGPACK_ADD_ENUM(ADDON_STATUS);
#endif
#ifndef MSGPACK_ADD_ENUM_ADDON_LOG
#define MSGPACK_ADD_ENUM_ADDON_LOG
MSGPACK_ADD_ENUM(ADDON_LOG);
#endif

namespace KODI
{
namespace ADDONS
{
namespace INTERFACE
{

/* Code below becomes on auto generation reused, hand edited parts should included here */
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2>---*/
/*---AUTO_GEN_PARSE<HAND_EDITED_FIELD_2_END>---*/

// Code here relates to direct API calls without use of shared mem from addon to Kodi.
//{{{

typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_GET_SETTING_BOOL_V1)(void*, const char*, bool*);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_GET_SETTING_FLOAT_V1)(void*,
                                                                         const char*,
                                                                         double*);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_GET_SETTING_INT_V1)(void*, const char*, int*);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_GET_SETTING_STRING_V1)(void*,
                                                                          const char*,
                                                                          char**);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_INSTANCE_GET_SETTING_BOOL_V1)(
    void*, const KODI_ADDON_INSTANCE_BACKEND_HDL, const char*, bool*);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_INSTANCE_GET_SETTING_FLOAT_V1)(
    void*, const KODI_ADDON_INSTANCE_BACKEND_HDL, const char*, double*);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_INSTANCE_GET_SETTING_INT_V1)(
    void*, const KODI_ADDON_INSTANCE_BACKEND_HDL, const char*, int*);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_INSTANCE_GET_SETTING_STRING_V1)(
    void*, const KODI_ADDON_INSTANCE_BACKEND_HDL, const char*, char**);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_INSTANCE_IS_SETTING_USING_DEFAULT_V1)(
    void*, const KODI_ADDON_INSTANCE_BACKEND_HDL, const char*);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_INSTANCE_SET_SETTING_BOOL_V1)(
    void*, const KODI_ADDON_INSTANCE_BACKEND_HDL, const char*, bool);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_INSTANCE_SET_SETTING_FLOAT_V1)(
    void*, const KODI_ADDON_INSTANCE_BACKEND_HDL, const char*, double);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_INSTANCE_SET_SETTING_INT_V1)(
    void*, const KODI_ADDON_INSTANCE_BACKEND_HDL, const char*, int);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_INSTANCE_SET_SETTING_STRING_V1)(
    void*, const KODI_ADDON_INSTANCE_BACKEND_HDL, const char*, const char*);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_IS_SETTING_USING_DEFAULT_V1)(void*, const char*);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_OPEN_SETTINGS_DIALOG_V1)(void*);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_SET_SETTING_BOOL_V1)(void*, const char*, bool);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_SET_SETTING_FLOAT_V1)(void*,
                                                                         const char*,
                                                                         double);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_SET_SETTING_INT_V1)(void*, const char*, int);
typedef bool(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_SET_SETTING_STRING_V1)(void*,
                                                                          const char*,
                                                                          const char*);
typedef char*(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_GET_ADDON_PATH_V1)(void*);
typedef char*(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_GET_INFO_V1)(void*, const char*);
typedef char*(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_GET_LIB_PATH_V1)(void*);
typedef char*(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_GET_TEMP_PATH_V1)(void*);
typedef char*(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_GET_USER_PATH_V1)(void*);
typedef char*(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_INSTANCE_GET_USER_PATH_V1)(
    void*, const KODI_ADDON_INSTANCE_BACKEND_HDL);
typedef char*(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_LOCALIZED_STRING_V1)(void*, long);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_LOG_V1)(void*, enum ADDON_LOG, const char*, ...);

struct directFuncToKodi_addon_base_h
{
  void* thisClassHdl;
  /* Function "kodi_check_main_shared" only used inside dev-kit library only */
  /* Function "kodi_deinit" only used inside dev-kit library only */
  /* Function "kodi_init" only used inside dev-kit library only */
  /* Function "kodi_process" only used inside dev-kit library only */
  PFN_INT_KODI_ADDON_GET_ADDON_PATH_V1 kodi_addon_get_addon_path_v1;
  PFN_INT_KODI_ADDON_GET_INFO_V1 kodi_addon_get_info_v1;
  PFN_INT_KODI_ADDON_GET_LIB_PATH_V1 kodi_addon_get_lib_path_v1;
  PFN_INT_KODI_ADDON_GET_SETTING_BOOL_V1 kodi_addon_get_setting_bool_v1;
  PFN_INT_KODI_ADDON_GET_SETTING_FLOAT_V1 kodi_addon_get_setting_float_v1;
  PFN_INT_KODI_ADDON_GET_SETTING_INT_V1 kodi_addon_get_setting_int_v1;
  PFN_INT_KODI_ADDON_GET_SETTING_STRING_V1 kodi_addon_get_setting_string_v1;
  PFN_INT_KODI_ADDON_GET_TEMP_PATH_V1 kodi_addon_get_temp_path_v1;
  PFN_INT_KODI_ADDON_GET_USER_PATH_V1 kodi_addon_get_user_path_v1;
  PFN_INT_KODI_ADDON_INSTANCE_GET_SETTING_BOOL_V1 kodi_addon_instance_get_setting_bool_v1;
  PFN_INT_KODI_ADDON_INSTANCE_GET_SETTING_FLOAT_V1 kodi_addon_instance_get_setting_float_v1;
  PFN_INT_KODI_ADDON_INSTANCE_GET_SETTING_INT_V1 kodi_addon_instance_get_setting_int_v1;
  PFN_INT_KODI_ADDON_INSTANCE_GET_SETTING_STRING_V1 kodi_addon_instance_get_setting_string_v1;
  PFN_INT_KODI_ADDON_INSTANCE_GET_USER_PATH_V1 kodi_addon_instance_get_user_path_v1;
  PFN_INT_KODI_ADDON_INSTANCE_IS_SETTING_USING_DEFAULT_V1
      kodi_addon_instance_is_setting_using_default_v1;
  PFN_INT_KODI_ADDON_INSTANCE_SET_SETTING_BOOL_V1 kodi_addon_instance_set_setting_bool_v1;
  PFN_INT_KODI_ADDON_INSTANCE_SET_SETTING_FLOAT_V1 kodi_addon_instance_set_setting_float_v1;
  PFN_INT_KODI_ADDON_INSTANCE_SET_SETTING_INT_V1 kodi_addon_instance_set_setting_int_v1;
  PFN_INT_KODI_ADDON_INSTANCE_SET_SETTING_STRING_V1 kodi_addon_instance_set_setting_string_v1;
  PFN_INT_KODI_ADDON_IS_SETTING_USING_DEFAULT_V1 kodi_addon_is_setting_using_default_v1;
  PFN_INT_KODI_ADDON_LOCALIZED_STRING_V1 kodi_addon_localized_string_v1;
  PFN_INT_KODI_ADDON_OPEN_SETTINGS_DIALOG_V1 kodi_addon_open_settings_dialog_v1;
  PFN_INT_KODI_ADDON_SET_SETTING_BOOL_V1 kodi_addon_set_setting_bool_v1;
  PFN_INT_KODI_ADDON_SET_SETTING_FLOAT_V1 kodi_addon_set_setting_float_v1;
  PFN_INT_KODI_ADDON_SET_SETTING_INT_V1 kodi_addon_set_setting_int_v1;
  PFN_INT_KODI_ADDON_SET_SETTING_STRING_V1 kodi_addon_set_setting_string_v1;
  PFN_INT_KODI_LOG_V1 kodi_log_v1;
};

//}}}

// Code here relates to direct API calls without use of shared mem from Kodi to addon.
//{{{

typedef KODI_ADDON_INSTANCE_HDL(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_INSTANCE_CREATE_V1)(
    void*, KODI_ADDON_INSTANCE_BACKEND_HDL);
typedef enum ADDON_STATUS(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_CREATE_INSTANCE_V1)(
    void*, const KODI_ADDON_HDL, const struct KODI_ADDON_INSTANCE_INFO*, KODI_HANDLE*);
typedef enum ADDON_STATUS(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_CREATE_V1)(
    void*, const struct KODI_ADDON_INSTANCE_INFO*, KODI_ADDON_HDL*);
typedef enum ADDON_STATUS(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_INSTANCE_SETTING_CHANGE_BOOLEAN_V1)(
    void*, const KODI_ADDON_HDL, const KODI_ADDON_INSTANCE_HDL, const char*, bool);
typedef enum ADDON_STATUS(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_INSTANCE_SETTING_CHANGE_FLOAT_V1)(
    void*, const KODI_ADDON_HDL, const KODI_ADDON_INSTANCE_HDL, const char*, double);
typedef enum ADDON_STATUS(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_INSTANCE_SETTING_CHANGE_INTEGER_V1)(
    void*, const KODI_ADDON_HDL, const KODI_ADDON_INSTANCE_HDL, const char*, int);
typedef enum ADDON_STATUS(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_INSTANCE_SETTING_CHANGE_STRING_V1)(
    void*, const KODI_ADDON_HDL, const KODI_ADDON_INSTANCE_HDL, const char*, const char*);
typedef enum ADDON_STATUS(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_SETTING_CHANGE_BOOLEAN_V1)(
    void*, const KODI_ADDON_HDL, const char*, bool);
typedef enum ADDON_STATUS(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_SETTING_CHANGE_FLOAT_V1)(
    void*, const KODI_ADDON_HDL, const char*, double);
typedef enum ADDON_STATUS(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_SETTING_CHANGE_INTEGER_V1)(
    void*, const KODI_ADDON_HDL, const char*, int);
typedef enum ADDON_STATUS(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_SETTING_CHANGE_STRING_V1)(
    void*, const KODI_ADDON_HDL, const char*, const char*);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_DESTROY_INSTANCE_V1)(
    void*, const KODI_ADDON_HDL, const struct KODI_ADDON_INSTANCE_INFO*, const KODI_HANDLE);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_DESTROY_V1)(void*, KODI_ADDON_HDL);
typedef void(ATTR_INT_APIENTRYP PFN_INT_KODI_ADDON_INSTANCE_DESTROY_V1)(void*,
                                                                        KODI_ADDON_INSTANCE_HDL);

struct directFuncToAddon_addon_base_h
{
  void* thisClassHdl;
  PFN_INT_KODI_ADDON_CREATE_INSTANCE_V1 kodi_addon_create_instance_v1;
  PFN_INT_KODI_ADDON_CREATE_V1 kodi_addon_create_v1;
  PFN_INT_KODI_ADDON_DESTROY_INSTANCE_V1 kodi_addon_destroy_instance_v1;
  PFN_INT_KODI_ADDON_DESTROY_V1 kodi_addon_destroy_v1;
  PFN_INT_KODI_ADDON_INSTANCE_CREATE_V1 kodi_addon_instance_create_v1;
  PFN_INT_KODI_ADDON_INSTANCE_DESTROY_V1 kodi_addon_instance_destroy_v1;
  PFN_INT_KODI_ADDON_INSTANCE_SETTING_CHANGE_BOOLEAN_V1
      kodi_addon_instance_setting_change_boolean_v1;
  PFN_INT_KODI_ADDON_INSTANCE_SETTING_CHANGE_FLOAT_V1 kodi_addon_instance_setting_change_float_v1;
  PFN_INT_KODI_ADDON_INSTANCE_SETTING_CHANGE_INTEGER_V1
      kodi_addon_instance_setting_change_integer_v1;
  PFN_INT_KODI_ADDON_INSTANCE_SETTING_CHANGE_STRING_V1 kodi_addon_instance_setting_change_string_v1;
  PFN_INT_KODI_ADDON_SETTING_CHANGE_BOOLEAN_V1 kodi_addon_setting_change_boolean_v1;
  PFN_INT_KODI_ADDON_SETTING_CHANGE_FLOAT_V1 kodi_addon_setting_change_float_v1;
  PFN_INT_KODI_ADDON_SETTING_CHANGE_INTEGER_V1 kodi_addon_setting_change_integer_v1;
  PFN_INT_KODI_ADDON_SETTING_CHANGE_STRING_V1 kodi_addon_setting_change_string_v1;
};

//}}}

/* Confirm after autogen the correctness here! */
/*---AUTO_GEN_PARSE<DATA_STRUCTURES>---*/

struct IFC_KODI_ADDON_INSTANCE_INFO
{
  IFC_KODI_ADDON_INSTANCE_INFO() = default;
  IFC_KODI_ADDON_INSTANCE_INFO(const KODI_ADDON_INSTANCE_INFO* c_data)
  {
    if (c_data == nullptr)
      return;

    type = c_data->type;
    instance_id = c_data->instance_id;
    if (c_data->unique_work_id)
      unique_work_id = c_data->unique_work_id;
    kodi = PtrValue(c_data->kodi);
    parent = PtrValue(c_data->parent);
  }

  void SetCStructure(KODI_ADDON_INSTANCE_INFO* c_data)
  {
    if (c_data == nullptr)
      return;

    c_data->type = type;
    c_data->instance_id = instance_id;
    c_data->unique_work_id = unique_work_id.c_str();
    c_data->kodi = reinterpret_cast<KODI_ADDON_INSTANCE_BACKEND_HDL>(kodi);
    c_data->parent = reinterpret_cast<KODI_ADDON_INSTANCE_HDL>(parent);
  }

  enum KODI_ADDON_INSTANCE_TYPE type;
  uint32_t instance_id;
  std::string unique_work_id;
  PtrValue kodi;
  PtrValue parent;

  MSGPACK_DEFINE(type, instance_id, unique_work_id, kodi, parent);
};
/*---AUTO_GEN_PARSE<DATA_STRUCTURES_END>---*/

typedef enum funcParent_addon_base_h : int
{
  funcParent_kodi_check_main_shared_v1,
  funcParent_kodi_init_v1,
  funcParent_kodi_deinit_v1,
  funcParent_kodi_process_v1,
  funcParent_kodi_log_v1,
  funcParent_kodi_addon_get_addon_path_v1,
  funcParent_kodi_addon_get_lib_path_v1,
  funcParent_kodi_addon_get_user_path_v1,
  funcParent_kodi_addon_get_temp_path_v1,
  funcParent_kodi_addon_localized_string_v1,
  funcParent_kodi_addon_get_info_v1,
  funcParent_kodi_addon_open_settings_dialog_v1,
  funcParent_kodi_addon_is_setting_using_default_v1,
  funcParent_kodi_addon_get_setting_bool_v1,
  funcParent_kodi_addon_get_setting_int_v1,
  funcParent_kodi_addon_get_setting_float_v1,
  funcParent_kodi_addon_get_setting_string_v1,
  funcParent_kodi_addon_set_setting_bool_v1,
  funcParent_kodi_addon_set_setting_int_v1,
  funcParent_kodi_addon_set_setting_float_v1,
  funcParent_kodi_addon_set_setting_string_v1,
  funcParent_kodi_addon_instance_get_user_path_v1,
  funcParent_kodi_addon_instance_is_setting_using_default_v1,
  funcParent_kodi_addon_instance_get_setting_bool_v1,
  funcParent_kodi_addon_instance_get_setting_int_v1,
  funcParent_kodi_addon_instance_get_setting_float_v1,
  funcParent_kodi_addon_instance_get_setting_string_v1,
  funcParent_kodi_addon_instance_set_setting_bool_v1,
  funcParent_kodi_addon_instance_set_setting_int_v1,
  funcParent_kodi_addon_instance_set_setting_float_v1,
  funcParent_kodi_addon_instance_set_setting_string_v1,
} funcParent_addon_base_h;

// clang-format off
/*---AUTO_GEN_PARSE<FUNC_PARENT_TUPLES>---*/
// Original API call: ATTR_DLL_EXPORT const char* kodi_check_main_shared(int argc, char* argv[]) __INTRODUCED_IN_KODI(1);
/* NOTE: msgParent__IN_kodi_check_main_shared - Override active to use inside dev-kit library only */
/* NOTE: msgParent_OUT_kodi_check_main_shared - Override active to use inside dev-kit library only */
// Original API call: ATTR_DLL_EXPORT KODI_IFC_HDL kodi_init(unsigned int api, int argc, char* argv[], struct KODI_ADDON_FUNC* func, bool via_main, bool no_receive) __INTRODUCED_IN_KODI(1);
/* NOTE: msgParent__IN_kodi_init - Override active to use inside dev-kit library only */
/* NOTE: msgParent_OUT_kodi_init - Override active to use inside dev-kit library only */
// Original API call: ATTR_DLL_EXPORT void kodi_deinit(KODI_IFC_HDL hdl) __INTRODUCED_IN_KODI(1);
/* NOTE: msgParent__IN_kodi_deinit - Override active to use inside dev-kit library only */
/* NOTE: msgParent_OUT_kodi_deinit - Override active to use inside dev-kit library only */
// Original API call: ATTR_DLL_EXPORT bool kodi_process(KODI_IFC_HDL hdl) __INTRODUCED_IN_KODI(1);
/* NOTE: msgParent__IN_kodi_process - Override active to use inside dev-kit library only */
/* NOTE: msgParent_OUT_kodi_process - Override active to use inside dev-kit library only */
// Original API call: ATTR_DLL_EXPORT void kodi_log(enum ADDON_LOG loglevel, const char* format, ...) __INTRODUCED_IN_KODI(1);
typedef std::tuple<ADDON_LOG, std::string> msgParent__IN_kodi_log_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgParent_OUT_kodi_log_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT char* kodi_addon_get_addon_path() __INTRODUCED_IN_KODI(1);
typedef std::tuple<DummyValue> msgParent__IN_kodi_addon_get_addon_path_v1; /* Autogenerated */
typedef std::tuple<std::string> msgParent_OUT_kodi_addon_get_addon_path_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT char* kodi_addon_get_lib_path() __INTRODUCED_IN_KODI(1);
typedef std::tuple<DummyValue> msgParent__IN_kodi_addon_get_lib_path_v1; /* Autogenerated */
typedef std::tuple<std::string> msgParent_OUT_kodi_addon_get_lib_path_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT char* kodi_addon_get_user_path() __INTRODUCED_IN_KODI(1);
typedef std::tuple<DummyValue> msgParent__IN_kodi_addon_get_user_path_v1; /* Autogenerated */
typedef std::tuple<std::string> msgParent_OUT_kodi_addon_get_user_path_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT char* kodi_addon_get_temp_path() __INTRODUCED_IN_KODI(1);
typedef std::tuple<DummyValue> msgParent__IN_kodi_addon_get_temp_path_v1; /* Autogenerated */
typedef std::tuple<std::string> msgParent_OUT_kodi_addon_get_temp_path_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT char* kodi_addon_localized_string(long label_id) __INTRODUCED_IN_KODI(1);
typedef std::tuple<long> msgParent__IN_kodi_addon_localized_string_v1; /* Autogenerated */
typedef std::tuple<std::string> msgParent_OUT_kodi_addon_localized_string_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT char* kodi_addon_get_info(const char* id) __INTRODUCED_IN_KODI(1);
typedef std::tuple<std::string> msgParent__IN_kodi_addon_get_info_v1; /* Autogenerated */
typedef std::tuple<std::string> msgParent_OUT_kodi_addon_get_info_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_addon_open_settings_dialog() __INTRODUCED_IN_KODI(1);
typedef std::tuple<DummyValue> msgParent__IN_kodi_addon_open_settings_dialog_v1; /* Autogenerated */
typedef std::tuple<bool> msgParent_OUT_kodi_addon_open_settings_dialog_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_addon_is_setting_using_default(const char* id) __INTRODUCED_IN_KODI(1);
typedef std::tuple<std::string> msgParent__IN_kodi_addon_is_setting_using_default_v1; /* Autogenerated */
typedef std::tuple<bool> msgParent_OUT_kodi_addon_is_setting_using_default_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_addon_get_setting_bool(const char* id, bool* value) __INTRODUCED_IN_KODI(1);
typedef std::tuple<std::string, bool> msgParent__IN_kodi_addon_get_setting_bool_v1; /* Autogenerated */
typedef std::tuple<bool, bool> msgParent_OUT_kodi_addon_get_setting_bool_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_addon_get_setting_int(const char* id, int* value) __INTRODUCED_IN_KODI(1);
typedef std::tuple<std::string, int> msgParent__IN_kodi_addon_get_setting_int_v1; /* Autogenerated */
typedef std::tuple<bool, int> msgParent_OUT_kodi_addon_get_setting_int_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_addon_get_setting_float(const char* id, double* value) __INTRODUCED_IN_KODI(1);
typedef std::tuple<std::string, double> msgParent__IN_kodi_addon_get_setting_float_v1; /* Autogenerated */
typedef std::tuple<bool, double> msgParent_OUT_kodi_addon_get_setting_float_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_addon_get_setting_string(const char* id, char** value) __INTRODUCED_IN_KODI(1);
typedef std::tuple<std::string> msgParent__IN_kodi_addon_get_setting_string_v1; /* Autogenerated */
typedef std::tuple<bool, std::string> msgParent_OUT_kodi_addon_get_setting_string_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_addon_set_setting_bool(const char* id, bool value) __INTRODUCED_IN_KODI(1);
typedef std::tuple<std::string, bool> msgParent__IN_kodi_addon_set_setting_bool_v1; /* Autogenerated */
typedef std::tuple<bool> msgParent_OUT_kodi_addon_set_setting_bool_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_addon_set_setting_int(const char* id, int value) __INTRODUCED_IN_KODI(1);
typedef std::tuple<std::string, int> msgParent__IN_kodi_addon_set_setting_int_v1; /* Autogenerated */
typedef std::tuple<bool> msgParent_OUT_kodi_addon_set_setting_int_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_addon_set_setting_float(const char* id, double value) __INTRODUCED_IN_KODI(1);
typedef std::tuple<std::string, double> msgParent__IN_kodi_addon_set_setting_float_v1; /* Autogenerated */
typedef std::tuple<bool> msgParent_OUT_kodi_addon_set_setting_float_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_addon_set_setting_string(const char* id, const char* value) __INTRODUCED_IN_KODI(1);
typedef std::tuple<std::string, std::string> msgParent__IN_kodi_addon_set_setting_string_v1; /* Autogenerated */
typedef std::tuple<bool> msgParent_OUT_kodi_addon_set_setting_string_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT char* kodi_addon_instance_get_user_path(const KODI_ADDON_INSTANCE_BACKEND_HDL hdl) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue> msgParent__IN_kodi_addon_instance_get_user_path_v1; /* Autogenerated */
typedef std::tuple<std::string> msgParent_OUT_kodi_addon_instance_get_user_path_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_addon_instance_is_setting_using_default( const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char* id) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string> msgParent__IN_kodi_addon_instance_is_setting_using_default_v1; /* Autogenerated */
typedef std::tuple<bool> msgParent_OUT_kodi_addon_instance_is_setting_using_default_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_addon_instance_get_setting_bool( const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char* id, bool* value) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string, bool> msgParent__IN_kodi_addon_instance_get_setting_bool_v1; /* Autogenerated */
typedef std::tuple<bool, bool> msgParent_OUT_kodi_addon_instance_get_setting_bool_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_addon_instance_get_setting_int( const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char* id, int* value) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string, int> msgParent__IN_kodi_addon_instance_get_setting_int_v1; /* Autogenerated */
typedef std::tuple<bool, int> msgParent_OUT_kodi_addon_instance_get_setting_int_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_addon_instance_get_setting_float( const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char* id, double* value) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string, double> msgParent__IN_kodi_addon_instance_get_setting_float_v1; /* Autogenerated */
typedef std::tuple<bool, double> msgParent_OUT_kodi_addon_instance_get_setting_float_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_addon_instance_get_setting_string( const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char* id, char** value) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string> msgParent__IN_kodi_addon_instance_get_setting_string_v1; /* Autogenerated */
typedef std::tuple<bool, std::string> msgParent_OUT_kodi_addon_instance_get_setting_string_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_addon_instance_set_setting_bool( const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char* id, bool value) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string, bool> msgParent__IN_kodi_addon_instance_set_setting_bool_v1; /* Autogenerated */
typedef std::tuple<bool> msgParent_OUT_kodi_addon_instance_set_setting_bool_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_addon_instance_set_setting_int( const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char* id, int value) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string, int> msgParent__IN_kodi_addon_instance_set_setting_int_v1; /* Autogenerated */
typedef std::tuple<bool> msgParent_OUT_kodi_addon_instance_set_setting_int_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_addon_instance_set_setting_float( const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char* id, double value) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string, double> msgParent__IN_kodi_addon_instance_set_setting_float_v1; /* Autogenerated */
typedef std::tuple<bool> msgParent_OUT_kodi_addon_instance_set_setting_float_v1; /* Autogenerated */
// Original API call: ATTR_DLL_EXPORT bool kodi_addon_instance_set_setting_string( const KODI_ADDON_INSTANCE_BACKEND_HDL hdl, const char* id, const char* value) __INTRODUCED_IN_KODI(1);
typedef std::tuple<PtrValue, std::string, std::string> msgParent__IN_kodi_addon_instance_set_setting_string_v1; /* Autogenerated */
typedef std::tuple<bool> msgParent_OUT_kodi_addon_instance_set_setting_string_v1; /* Autogenerated */
/*---AUTO_GEN_PARSE<FUNC_PARENT_TUPLES_END>---*/
// clang-format on

//==============================================================================

typedef enum funcChild_addon_base_h : int
{
  funcChild_kodi_addon_create_v1,
  funcChild_kodi_addon_destroy_v1,
  funcChild_kodi_addon_setting_change_string_v1,
  funcChild_kodi_addon_setting_change_boolean_v1,
  funcChild_kodi_addon_setting_change_integer_v1,
  funcChild_kodi_addon_setting_change_float_v1,
  funcChild_kodi_addon_create_instance_v1,
  funcChild_kodi_addon_destroy_instance_v1,
  funcChild_kodi_addon_instance_setting_change_string_v1,
  funcChild_kodi_addon_instance_setting_change_boolean_v1,
  funcChild_kodi_addon_instance_setting_change_integer_v1,
  funcChild_kodi_addon_instance_setting_change_float_v1,
  funcChild_kodi_addon_instance_create_v1,
  funcChild_kodi_addon_instance_destroy_v1,
} funcChild_addon_base_h;

// clang-format off
/*---AUTO_GEN_PARSE<FUNC_CHILD_TUPLES>---*/
// Original API call: typedef enum ADDON_STATUS(ATTR_APIENTRYP PFN_KODI_ADDON_CREATE_V1)(const struct KODI_ADDON_INSTANCE_INFO* first_instance, KODI_ADDON_HDL* hdl);
typedef std::tuple<IFC_KODI_ADDON_INSTANCE_INFO> msgChild__IN_kodi_addon_create_v1; /* Autogenerated */
typedef std::tuple<ADDON_STATUS, PtrValue> msgChild_OUT_kodi_addon_create_v1; /* Autogenerated */
// Original API call: typedef void(ATTR_APIENTRYP PFN_KODI_ADDON_DESTROY_V1)(KODI_ADDON_HDL hdl);
typedef std::tuple<PtrValue> msgChild__IN_kodi_addon_destroy_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgChild_OUT_kodi_addon_destroy_v1; /* Autogenerated */
// Original API call: typedef enum ADDON_STATUS(ATTR_APIENTRYP PFN_KODI_ADDON_SETTING_CHANGE_STRING_V1)(const KODI_ADDON_HDL hdl, const char* name, const char* value);
typedef std::tuple<PtrValue, std::string, std::string> msgChild__IN_kodi_addon_setting_change_string_v1; /* Autogenerated */
typedef std::tuple<ADDON_STATUS> msgChild_OUT_kodi_addon_setting_change_string_v1; /* Autogenerated */
// Original API call: typedef enum ADDON_STATUS(ATTR_APIENTRYP PFN_KODI_ADDON_SETTING_CHANGE_BOOLEAN_V1)(const KODI_ADDON_HDL hdl, const char* name, bool value);
typedef std::tuple<PtrValue, std::string, bool> msgChild__IN_kodi_addon_setting_change_boolean_v1; /* Autogenerated */
typedef std::tuple<ADDON_STATUS> msgChild_OUT_kodi_addon_setting_change_boolean_v1; /* Autogenerated */
// Original API call: typedef enum ADDON_STATUS(ATTR_APIENTRYP PFN_KODI_ADDON_SETTING_CHANGE_INTEGER_V1)(const KODI_ADDON_HDL hdl, const char* name, int value);
typedef std::tuple<PtrValue, std::string, int> msgChild__IN_kodi_addon_setting_change_integer_v1; /* Autogenerated */
typedef std::tuple<ADDON_STATUS> msgChild_OUT_kodi_addon_setting_change_integer_v1; /* Autogenerated */
// Original API call: typedef enum ADDON_STATUS(ATTR_APIENTRYP PFN_KODI_ADDON_SETTING_CHANGE_FLOAT_V1)(const KODI_ADDON_HDL hdl, const char* name, double value);
typedef std::tuple<PtrValue, std::string, double> msgChild__IN_kodi_addon_setting_change_float_v1; /* Autogenerated */
typedef std::tuple<ADDON_STATUS> msgChild_OUT_kodi_addon_setting_change_float_v1; /* Autogenerated */
// Original API call: typedef enum ADDON_STATUS(ATTR_APIENTRYP PFN_KODI_ADDON_CREATE_INSTANCE_V1)(const KODI_ADDON_HDL hdl, const struct KODI_ADDON_INSTANCE_INFO* info, struct KODI_ADDON_INSTANCE_STRUCT* instance);
typedef std::tuple<PtrValue, IFC_KODI_ADDON_INSTANCE_INFO> msgChild__IN_kodi_addon_create_instance_v1; /* OVERRIDE;USE_HAND_MAKE used, set this by hand */
typedef std::tuple<ADDON_STATUS, PtrValue> msgChild_OUT_kodi_addon_create_instance_v1; /* OVERRIDE;USE_HAND_MAKE used, set this by hand */
// Original API call: typedef void(ATTR_APIENTRYP PFN_KODI_ADDON_DESTROY_INSTANCE_V1)(const KODI_ADDON_HDL hdl, const struct KODI_ADDON_INSTANCE_INFO* info, const KODI_ADDON_INSTANCE_HDL instance_hdl);
typedef std::tuple<PtrValue, IFC_KODI_ADDON_INSTANCE_INFO, PtrValue> msgChild__IN_kodi_addon_destroy_instance_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgChild_OUT_kodi_addon_destroy_instance_v1; /* Autogenerated */
// Original API call: typedef enum ADDON_STATUS(ATTR_APIENTRYP PFN_KODI_ADDON_INSTANCE_SETTING_CHANGE_STRING_V1)(const KODI_ADDON_HDL hdl, const KODI_ADDON_INSTANCE_HDL instance_hdl, const char* name, const char* value);
typedef std::tuple<PtrValue, PtrValue, std::string, std::string> msgChild__IN_kodi_addon_instance_setting_change_string_v1; /* Autogenerated */
typedef std::tuple<ADDON_STATUS> msgChild_OUT_kodi_addon_instance_setting_change_string_v1; /* Autogenerated */
// Original API call: typedef enum ADDON_STATUS(ATTR_APIENTRYP PFN_KODI_ADDON_INSTANCE_SETTING_CHANGE_BOOLEAN_V1)(const KODI_ADDON_HDL hdl, const KODI_ADDON_INSTANCE_HDL instance_hdl, const char* name, bool value);
typedef std::tuple<PtrValue, PtrValue, std::string, bool> msgChild__IN_kodi_addon_instance_setting_change_boolean_v1; /* Autogenerated */
typedef std::tuple<ADDON_STATUS> msgChild_OUT_kodi_addon_instance_setting_change_boolean_v1; /* Autogenerated */
// Original API call: typedef enum ADDON_STATUS(ATTR_APIENTRYP PFN_KODI_ADDON_INSTANCE_SETTING_CHANGE_INTEGER_V1)(const KODI_ADDON_HDL hdl, const KODI_ADDON_INSTANCE_HDL instance_hdl, const char* name, int value);
typedef std::tuple<PtrValue, PtrValue, std::string, int> msgChild__IN_kodi_addon_instance_setting_change_integer_v1; /* Autogenerated */
typedef std::tuple<ADDON_STATUS> msgChild_OUT_kodi_addon_instance_setting_change_integer_v1; /* Autogenerated */
// Original API call: typedef enum ADDON_STATUS(ATTR_APIENTRYP PFN_KODI_ADDON_INSTANCE_SETTING_CHANGE_FLOAT_V1)(const KODI_ADDON_HDL hdl, const KODI_ADDON_INSTANCE_HDL instance_hdl, const char* name, double value);
typedef std::tuple<PtrValue, PtrValue, std::string, double> msgChild__IN_kodi_addon_instance_setting_change_float_v1; /* Autogenerated */
typedef std::tuple<ADDON_STATUS> msgChild_OUT_kodi_addon_instance_setting_change_float_v1; /* Autogenerated */
// Original API call: typedef KODI_ADDON_INSTANCE_HDL(ATTR_APIENTRYP PFN_KODI_ADDON_INSTANCE_CREATE_V1)(KODI_ADDON_INSTANCE_BACKEND_HDL kodi_hdl);
typedef std::tuple<PtrValue> msgChild__IN_kodi_addon_instance_create_v1; /* Autogenerated */
typedef std::tuple<PtrValue> msgChild_OUT_kodi_addon_instance_create_v1; /* Autogenerated */
// Original API call: typedef void(ATTR_APIENTRYP PFN_KODI_ADDON_INSTANCE_DESTROY_V1)(KODI_ADDON_INSTANCE_HDL hdl);
typedef std::tuple<PtrValue> msgChild__IN_kodi_addon_instance_destroy_v1; /* Autogenerated */
typedef std::tuple<DummyValue> msgChild_OUT_kodi_addon_instance_destroy_v1; /* Autogenerated */
/*---AUTO_GEN_PARSE<FUNC_CHILD_TUPLES_END>---*/
// clang-format on

} /* namespace INTERFACE */
} /* namespace ADDONS */
} /* namespace KODI */
